doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            App\EmailSender\Infrastructure\Orm\EmailIdType: App\EmailSender\Infrastructure\Orm\EmailIdType
            App\EmailSender\Infrastructure\Orm\EmailMessageStatusType: App\EmailSender\Infrastructure\Orm\EmailMessageStatusType
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App\EmailSender:
                type: yml
                dir: '%kernel.project_dir%/src/EmailSender/Infrastructure/Orm'
                is_bundle: false
                prefix: 'App\EmailSender\Domain'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
