version: '3.9'

services:

  nginx:
    image: nginx:1.22
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    expose:
      - 80
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini-development:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    tty: true
    expose:
      - 9003
    environment:
      PHP_IDE_CONFIG: 'serverName=application'
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: cqrs-example
      POSTGRES_PASSWORD: password
      POSTGRES_USER: cqrs-symfony
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
